### ISSUE TITLE
Основные объекты

### ISSUE THREAD

**Issue by ShizoDevelopment** [ShizNa/FinAssistant#1]
Пользователь(User) <-> Роли(Role)
К пользователю крепится баланс (Balance)
В балансе есть статьи/аккаунты (Account). Каждый аккаунт имеет описание (description), тип (положительный или отрицательный; type), объем (сумму числом; Amount) и валюту (CCY)

**Comment by Nakods** [comment]
Предложение по структуре, наименования обернул в точки, в миграциях их не будет
.Users.
                id
                login
                last_name
                first_name
                middle_name
                birthday
                email
                phone
                active
                create_date
                modify_date

.Roles.
                id
                object_name
                descrioption
                create_date
                modify_date
             
.Permissions.
                id
                user_id
                role_id
                create_date
                modify_date

.Balances.
                id
                object_name
                description
                user_id
                create_date
                modify_date          

.Accounts.
                id
                object_name
                description
                type
                amount
                ccy
                balance_id
                create_date
                modify_date
